"""add interest columns in user

Revision ID: 11b47b263a7d
Revises: a6f8f96420da
Create Date: 2026-05-16 16:03:16.597761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11b47b263a7d'
down_revision = 'a6f8f96420da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interest_2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interest_3', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('interest_3')
        batch_op.drop_column('interest_2')
        batch_op.drop_column('interest_1')

    # ### end Alembic commands ###
