"""add recurrence type to availability

Revision ID: 150c9a78a543
Revises: f4b6acfb4f20
Create Date: 2026-05-14 23:31:04.665434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150c9a78a543'
down_revision = 'f4b6acfb4f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_column('recurrence')

    # ### end Alembic commands ###
