"""add interests table

Revision ID: a6f8f96420da
Revises: 76535cf9a237
Create Date: 2026-05-16 15:48:21.689575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6f8f96420da'
down_revision = '76535cf9a237'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    if not bind.dialect.has_table(bind, 'interest'):
        op.create_table('interest',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interest')
    # ### end Alembic commands ###
