"""add recurring fields to availability

Revision ID: c47f522120c2
Revises: fb09d0567d85
Create Date: 2026-05-14 19:09:22.171032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47f522120c2'
down_revision = 'fb09d0567d85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recurrence_end', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_column('recurrence_end')
        batch_op.drop_column('is_recurring')

    # ### end Alembic commands ###
