"""add recurrence_group_id to availability

Revision ID: f4b6acfb4f20
Revises: c47f522120c2
Create Date: 2026-05-14 22:45:11.926721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4b6acfb4f20'
down_revision = 'c47f522120c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurrence_group_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_column('recurrence_group_id')

    # ### end Alembic commands ###
